preload = ~/wallpapers/wallpaper1.png
preload = ~/wallpapers/wallpaper2.jpg
preload = ~/wallpapers/wallpaper3.png
preload = ~/wallpapers/wallpaper4.jpg
preload = ~/wallpapers/wallpaper5.jpg
preload = ~/wallpapers/wallpaper6.jpg
preload = ~/wallpapers/wallpaper7.jpg
preload = ~/wallpapers/wallpaper8.png
preload = ~/wallpapers/wallpaper9.jpg
preload = ~/wallpapers/wallpaper10.jpg
preload = ~/wallpapers/wallpaper11.jpg
preload = ~/wallpapers/wallpaper12.jpg
preload = ~/wallpapers/wallpaper13.jpg
preload = ~/wallpapers/wallpaper14.jpg
preload = ~/wallpapers/wallpaper15.jpg
preload = ~/wallpapers/wallpaper16.jpg
preload = ~/wallpapers/wallpaper17.jpg
wallpaper = ,~/wallpapers/wallpaper14.jpg
