#####################
### LOOK AND FEEL ###
#####################

general {
    gaps_in = 2
    gaps_out = 4

    border_size = 2

    no_focus_fallback = true

    col.active_border   = rgba(c8d3f5ee)
    col.inactive_border = rgba(222436ff)

    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 10          # blocky corners
    rounding_power = 2    # irrelevant with 0 rounding

    active_opacity = 0.8  # fully solid
    inactive_opacity = 0.8

    dim_inactive = false
    dim_strength = 0.0

    shadow {
        enabled = false    # no shadow for blocky feel
    }

    blur {
        enabled = true
        size = 8
        passes = 2
    }
}

animations {
    enabled = yes, please :)

    bezier = myBezier, 0.10, 0.9, 0.1, 1.05

    animation = windows, 1, 1, myBezier, slide
    animation = windowsOut, 1, 1, myBezier, slide
    animation = border, 1, 10, default
    animation = fade, 1, 2, default
    animation = workspaces, 1, 3, default
}

# dwindle {
#     pseudotile = true
#     preserve_split = true
# }

master {
    new_status = master
}

cursor {
    inactive_timeout = 1
}

misc {
    force_default_wallpaper = 0
    focus_on_activate = true
    disable_hyprland_logo = true
}
