# Retro Tmux Theme

set -g status-style bg=#222436,fg=#c8d3f5
set -g status-left "#[fg=#ffc777,bold]#S #[fg=#c8d3f5]| "
set -g status-right "#[fg=#c8d3f5]| #[fg=#ffc777]%Y-%m-%d #[fg=#c8d3f5]%H:%M #[fg=#c8d3f5]| #[fg=#ffc777]#h"
set -g window-status-format "#[fg=#c8d3f5,bg=#222436] #I #W "
set -g window-status-current-format "#[fg=#ffc777,bg=#222436,bold] #I #W "
