#####################
### LOOK AND FEEL ###
#####################

general {
    gaps_in = 04
    gaps_out = 010

    border_size = 00

    no_focus_fallback = true

    col.active_border   = rgba(268bd2ff)
    col.inactive_border = rgba(657b8399)

    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 10
    rounding_power = 3

    active_opacity = 1.0
    inactive_opacity = 1.0

    dim_inactive = true
    dim_strength = 0.1

    shadow {
        enabled = true
        range = 10
        render_power = 4
        color = rgba(7a847877)
    }

    blur {
        enabled = true
        size = 1
        passes = 3
        noise = 0.1
        vibrancy = 1.0
    }
}

animations {
    enabled = yes, please :)

    bezier = myBezier, 0.10, 0.9, 0.1, 1.05

    animation = windows, 1, 1, myBezier, slide
    animation = windowsOut, 1, 1, myBezier, slide
    animation = border, 1, 10, default
    animation = fade, 1, 2, default
    animation = workspaces, 1, 3, default
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

cursor {
    inactive_timeout = 1
}

misc {
    force_default_wallpaper = 0
    focus_on_activate = true
    disable_hyprland_logo = true
}
