set -g status-style bg=#1e2326,fg=#f2efdf

set -g status-left "#[fg=#f2efdf,bold]#S #[fg=#a6b0a0]| "
set -g status-right "#[fg=#a6b0a0]| #[fg=#f2efdf]%Y-%m-%d #[fg=#f2efdf]%H:%M #[fg=#a6b0a0]| #[fg=#df69ba]#h"

set -g window-status-format "#[fg=#a6b0a0,bg=#1e2326] #I #W "
set -g window-status-current-format "#[fg=#f2efdf,bg=#1e2326,bold] #I #W "

set -wg mode-style "fg=#fffbef,bg=#4c3743"
