# /etc/lightdm/lightdm.conf

[LightDM]
run-directory=/run/lightdm

[Seat:*]
greeter-session=lightdm-slick-greeter
user-session=hyprland
session-wrapper=lightdm-session
autologin-user=
autologin-user-timeout=0
autologin-session=

[XDMCPServer]
enabled=false

[VNCServer]
enabled=false
