# /etc/lightdm/slick-greeter.conf

[Greeter]
background = /usr/share/backgrounds/hyprland.png
screen-padding = 0
font-name = Fira Code Nerd Font 12
text-color = #ebdbb2
background-color = #1d2021
theme-name = Adwaita-dark
icon-theme-name = Adwaita
cursor-theme-name = Adwaita
draw-user-backgrounds = false
draw-grid = false
show-clock = true
clock-format = %H:%M
xft-rgba = none
xft-hintstyle = hintnone
xft-antialias = false
enable-hidpi = auto
