[window]
opacity = 0.82
blur = true

[window.padding]
x = 10
y = 15

[colors.primary]
# background = "#440011"
# background = "#181818"
# background = "#112233"
background = "#221122"

[font]
size = 15

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"
